version: '2'
services:
  wabnet:
    container_name: wabnet
    image: wabnet
    environment:
      - "SECRET_KEY=${SECRET_KEY}"
      - "EC5_PROJECT_NAME=${EC5_PROJECT_NAME}"
      - "EC5_SECRET_KEY=${EC5_SECRET_KEY}"
      - "EC5_CLIENT_ID=${EC5_CLIENT_ID}"
      - "DEBUG=True"
      - "STATIC_ROOT=/static"
      - "MEDIA_ROOT=/media"
    restart: unless-stopped
    volumes:
      - static:/static
      - media:/media

  apache:
    container_name: wabnet-apache
    image: "httpd:2.4.33"
    ports:
      - "6080:80"
    restart: unless-stopped
    volumes:
        - static:/static
        - media:/media
        - "/wabnet-compose/httpd.conf:/usr/local/apache2/conf/httpd.conf:ro"

volumes:
  static:
    driver: local
  media:
    driver: local
