birt:
  container_name: birt
  image: birt
  environment:
    - MONGO_URL=mongodb://10.0.0.205:27017/birt
    - MONGO_URI=mongodb://10.0.0.205:27017
    - MONGO_HOST=10.0.0.205
    - MONGO_DB=birt
    - MONGO_PORT=27017
    - SIMULATION_PORT=45000
    - ROOT_URL=http://birt.eha.io
    - PORT=80
  ports:
    - "80:80"
  restart: always
  command: supervisord --nodaemon --config /etc/supervisor/supervisord.conf

mongodb:
  container_name: mongodb
  image: mongodb
  ports:
    - "27017:27017"
  restart: always
  volumes:
    - /mnt/mongo:/var/lib
    - /var/log:/var/log

