docker-registry:
  container_name: docker-registry
  image: registry
  ports:
    - "5000:5000"
  environment:
    - SETTINGS_FLAVOR=s3
    - AWS_BUCKET=eha-devops-docker-registry
    - STORAGE_PATH=/registry
    - SEARCH_BACKEND=sqlalchemy
  restart: always
