flirt:
  container_name: flirt
  image: flirt
  environment:
    - MONGO_URL=mongodb://172.16.158.136:27017/grits
    - MONGO_URI=mongodb://172.16.158.136:27017
    - MONGO_HOST=172.16.158.136
    - MONGO_DB=grits
    - MONGO_PORT=27017
    - SIMULATION_PORT=45000
    - ROOT_URL=http://localhost
    - PORT=80
  ports:
    - "80:80"
  restart: always
  command: supervisord --nodaemon --config /etc/supervisor/supervisord.conf

