flirt:
  container_name: flirt
  image: flirt
  environment:
    - MONGO_URL=mongodb://10.0.0.175:27017/grits-net-meteor
    - ROOT_URL=http://52.23.65.236
    - PORT=80 
  ports:
    - "80:80"
  restart: always
  command: supervisord --nodaemon --config /etc/supervisor/supervisord.conf
