flirt:
  container_name: flirt
  image: flirt
  environment:
    - MONGO_URL=mongodb://10.0.0.176:27017/flirt
    - MONGO_URI=mongodb://10.0.0.176:27017
    - MONGO_HOST=10.0.0.176
    - MONGO_DB=flirt
    - MONGO_PORT=27017
    - SIMULATION_PORT=45000
    - ROOT_URL=http://52.23.65.236
    - PORT=3000
    - TERM=xterm
  ports:
    - "3000:3000"
  restart: always
  volumes:
    - /shared:/shared:ro
  command: supervisord --nodaemon --config /etc/supervisor/supervisord.conf

