grits:
  image: grits
  container_name: grits
  ports:
    - "3001:3001"
    - "25:25"
    - "80:80"
    - "443:443"
  restart: always
  volumes:
    - /etc/letsencrypt:/etc/letsencrypt
    - /shared:/shared

redis:
  image: redis
  container_name: redis
  ports:
    - "6379:6379"
  restart: always

mongodb:
  container_name: mongodb
  image: mongodb
  ports:
    - "27017:27017"
  restart: always
  volumes:
    - /mnt/mongo:/var/lib
    - /var/log:/var/log

