redis-tunnel:
  container_name: redis-tunnel
  image: thomass/ssh-client
  volumes:
    - ~/.ssh:/ssh
  command: "ssh -Ng -L 6379:localhost:6379 -i /ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@grits.eha.io"
  ports:
    - "6379:6379"
  restart: always

grits:
  image: grits
  container_name: grits
  links:
    - redis-tunnel
  restart: always
  command: sleep 100000
  environment:
    - 'BROKER_URL=redis://redis-tunnel:6379/0'
    - 'AUTOSTART_APACHE=false'
    - 'AUTOSTART_DASHBOARD=false'
    - 'PRIORITY_WORKERS=1'
    - 'DIAGNOSE_WORKERS=1'
    - 'PROCESS_WORKERS=10'
