grits:
  image: grits
  container_name: grits
  ports:
    - "3001:3001"
    - "25:25"
    - "80:80"
    - "443:443"
  restart: always
  volumes:
    - /etc/letsencrypt:/etc/letsencrypt

redis:
  image: redis
  container_name: redis
  ports:
    - "6379:6379"
  restart: always
