grits:
  image: grits
  container_name: grits
  ports:
    - "3000:3000"
    - "25:25"
    - "80:80"
    - "443:443"
  restart: always
  environment:
    - GIRDER_MONGO_URI=mongodb://grits.eha.io:27017/girder
    - MONGO_URL=mongodb://grits.eha.io:27017/
    - TERM=xterm

