mobile-survey:
  container_name: mobile-survey
  image: mobile-survey
  environment:
    - MONGO_URL=mongodb://10.0.0.13:27017/survey
    - ROOT_URL=http://survey.eha.io
    - PORT=3000
  ports:
    - "3000:3000"
  restart: always
  volumes:
    - /shared:/shared
  command: supervisord --nodaemon --config /etc/supervisor/supervisord.conf
