mongodb:
  container_name: mongodb
  image: docker-repository.tater.io:5000/devops/mongodb
  ports:
    - "27017:27017"
  restart: always
  volumes:
    - /mnt/mongo:/var/lib
    - /var/log:/var/log

