spa:
  container_name: spa
  image: spa
  environment:
    - MONGO_URL=mongodb://10.0.0.175:27017/promed
    - PORT=80 
  ports:
    - "80:80"
  restart: always
  command: supervisord --nodaemon --config /etc/supervisor/supervisord.conf