spa:
  container_name: spa
  image: spa
  environment:
    - MONGO_URL=mongodb://172.16.158.138:27017/promed
    - ROOT_URL=http://54.174.42.80
    - PORT=80 
  ports:
    - "80:80"
  restart: always
  command: supervisord --nodaemon --config /etc/supervisor/supervisord.conf