version: '2'
services:
  sshd:
    image: sshd
    restart: always
    ports:
      - "6322:22"
    networks:
      - tunnel
  # Create permanent volume so host keys don't change on redeploy
  volumes:
    - "/sshd/etc:/etc/ssh"

networks:
  tunnel:
