- name: Copy compose directory
  synchronize: src="compose/" dest="/sshd"
- name: Build sshd image
  docker_image:
    path: /sshd
    name: sshd
    force: yes
- name: Start sshd service
  docker_service:
    project_src: /sshd
