#!/bin/bash

export CLASSIFIER_DATA_ACCESS_KEY=""
export CLASSIFIER_DATA_SECRET_KEY=""
export GIRDER_DATA_ACCESS_KEY=""
export GIRDER_DATA_SECRET_KEY=""

export MONGO_URL=""
export CELERY_BROKER=""

export APACHE_URL=""
export GIRDER_MOUNT_PATH=""
export GIRDER_ADMIN_PASSWORD=""
export GIRDER_ADMIN_EMAIL=""

# Be careful to use different dump directories for production and development
export S3_MONGO_IMPORT_DIRECTORY=""
export S3_DUMP_DIRECTORY=""

export BING_TRANSLATE_ID=""
export BING_TRANSLATE_SECRET=""

export METEOR_DB_NAME=""
export METEOR_MONGO=""
export METEOR_PORT=""
