redis-tunnel:
  container_name: redis-tunnel
  image: thomass/ssh-client
  volumes:
    # TODO: Deploy key from ansible
    - /home/freddie/.ssh:/ssh
  command: "ssh -Ng -L 6379:localhost:6379 -i /ssh/id_rsa -o StrictHostKeyChecking=no ubuntu@grits.eha.io"
  ports:
    - "6379"
  restart: always

grits:
  image: grits
  container_name: grits
  links:
    - redis-tunnel
  restart: always
  environment:
    - 'BROKER_URL=redis://redis-tunnel:6379/0'
    - 'AUTOSTART_APACHE=false'
    - 'AUTOSTART_DASHBOARD=false'
    - 'AUTOSTART_PROCESS_WORKERS=false'
    - 'AUTOSTART_PRIORITY_WORKERS=false'
    - 'DIAGNOSE_WORKERS=2'
    - 'GOOGLE_TRANSLATE_KEY=${google_translate_key}'
