version: '2'
services:
  app:
    image: eidr-connect
    container_name: ${domain_name}
    environment:
      # Mongo is deployed by another compose file.
      - MONGO_URL=mongodb://${ip_address}:27017/${db_name}
      - ROOT_URL=https://${domain_name}
      - PORT=3000
      - SPA_MONGO_URL=mongodb://${ip_address}:27018/promed
    env_file:
      - /shared/${domain_name}/sensitive-environment-vars.env
    ports:
      - "${port}:3000"
    restart: always
    volumes:
      - /shared/${domain_name}:/shared
