version: '2'
services:
  app:
    image: eidr-connect
    container_name: ${root_url}
    environment:
      # Mongo is deployed by another compose file.
      - MONGO_URL=mongodb://${ip_address}:27017/eidr-connect-bsve
      - ROOT_URL=https://${root_url}
      - PORT=3000
      - SPA_MONGO_URL=mongodb://${ip_address}:27018/promed
    env_file:
      - /shared/sensitive-environment-vars.env
    ports:
      - "3180:3000"
    restart: always
    volumes:
      - /shared/${root_url}:/shared
