docker-registry:
  container_name: docker-registry
  image: registry
  ports:
    - "5000:5000"
  environment:
    - SETTINGS_FLAVOR=s3
    - AWS_BUCKET=eha-devops-docker-registry
    - STORAGE_PATH=/registry
    - AWS_KEY=AKIAJVECOZYOARNIRYXA
    - AWS_SECRET=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
    - SEARCH_BACKEND=sqlalchemy
  mem_limit: 2g
  restart: always

healthcheck:
  container_name: docker-repository.tater.io/devops/healthcheck
  image: healthcheck
  ports:
    - "8000:8000"
  restart: always
