docker-registry:
  container_name: docker-registry
  image: registry
  ports:
    - "5000:5000"
  environment:
    - SETTINGS_FLAVOR=s3
    - AWS_BUCKET=eha-devops-docker-registry
    - STORAGE_PATH=/registry
    - AWS_KEY=AKIAJVECOZYOARNIRYXA
    - AWS_SECRET=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
    - SEARCH_BACKEND=sqlalchemy
  restart: always

healthcheck:
  container_name: healthcheck
  image: docker-repository.tater.io:5000/devops/healthcheck
  ports:
    - "8000:80"
  restart: always

eha.tater.io:
  container_name: eha.tater.io
  image: docker-repository.tater.io:5000/apps/tater
  ports:
    - "8001:3000"
  restart: always
  environment:
    - MONGO_URL=mongodb://10.0.0.92:27017/eha

