---
- hosts: targets
  become: yes
  become_user: root
  vars:
    infrastructure_root: "../.."
    save_images: true
    domain_name: "niam.eha.io"
    webroot: "/var/www"
    ssl_directory: "/etc/letsencrypt/live/{{domain_name}}"
    keypath: "{{ssl_directory}}/privkey.pem"
    certpath: "{{ssl_directory}}/cert.pem"
    chainpath: "{{ssl_directory}}/chain.pem"
    fullchainpath: "{{ssl_directory}}/fullchain.pem"
    acme_tiny_challenges_directory: "/var/www/.well-known/acme-challenge"
    meteor_port: 3000
    apache_extra_parameters: |
      RewriteEngine on
      RewriteRule ^/internal.* [F]
      RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
      RewriteCond %{HTTP:CONNECTION} ^Upgrade$ [NC]
      RewriteRule ^/(?!\.well-known)(.*) ws://localhost:{{ meteor_port }}%{REQUEST_URI} [P]
      RewriteCond %{HTTPS} off
      RewriteRule (.*) https://%{SERVER_NAME}/ [R,L]
      ProxyPreserveHost On
      ProxyPassMatch ^/(?!\.well-known)(.*) http://localhost:{{ meteor_port }}/$1
      ProxyPassReverse ^/(?!\.well-known)(.*) http://localhost:{{ meteor_port }}/$1
  roles:
    - name: init
      tags: init
    - name: kamaln7.swapfile
      swapfile_size: 16GB
      swapfile_location: "/swapfile"
      tags: swap
    - name: angstwad.docker_ubuntu
      # Due to this bug the version need to be pinned.
      # https://github.com/ansible/ansible/issues/20492
      pip_version_docker_compose: '1.9.0'
      pip_version_docker_py: '1.10.6'
      tags: docker
    - name: thefinn93.letsencrypt
      letsencrypt_cert_domains:
        - "{{domain_name}}"
      letsencrypt_webroot_path: "{{webroot}}"
      letsencrypt_email: "tech@ecohealthalliance.org"
      tags: letsencrypt
    - name: geerlingguy.apache
      apache_mods_enabled:
        - rewrite.load
        - ssl.load
        - proxy.load
        - proxy_http.load
        - alias.load
        - proxy_wstunnel.load
      apache_mods_disabled: []
      apache_vhosts_ssl:
        - servername: "{{domain_name}}"
          documentroot: "{{webroot}}"
          certificate_file: "{{certpath}}"
          certificate_key_file: "{{keypath}}"
          certificate_chain_file: "{{chainpath}}"
          extra_parameters: "{{apache_extra_parameters}}"
      apache_vhosts:
        - servername: "{{domain_name}}"
          documentroot: "{{webroot}}"
          extra_parameters: "{{apache_extra_parameters}}"
      tags: apache
    - name: niam
      tags: niam
    # The virtuoso container may have problems.
    # The first time you build and launch it, it might crash, but work when restarted.
    # It might not stop gracefully and leaves a lock file that needs to be deleted.
    # When it is started with a new dump to load, it will take at least an hour to load the full dataset,
    # and if the machine doesn't have enough resources it might get stuck.
    # When restarting it, you may need to wait for the transactions to replay.
    - name: virtuoso
      tags: virtuoso
    - name: cron_backup
      tags: cron_backup
  vars_files:
    - secure.yml
