---
- hosts: targets
  become: yes
  become_user: root
  vars:
    infrastructure_root: "../.."
    save_images: true
  roles:
    - name: init
      tags: init
    - name: kamaln7.swapfile
      swapfile_size: 16GB
      swapfile_location: "/swapfile"
      tags: swap
    - name: angstwad.docker_ubuntu
      tags: docker
    - name: niam
      tags: niam
    # The virtuoso container may have problems.
    # The first time you build and launch it, it might crash, but work when restarted.
    # It might not stop gracefully and leaves a lock file that needs to be deleted.
    # When it is started with a new dump to load, it will take at least an hour to load the full dataset,
    # and if the machine doesn't have enough resources it might get stuck.
    # When restarting it, you may need to wait for the transactions to replay.
    - name: virtuoso
      tags: virtuoso
    - name: cron_backup
      tags: cron_backup
  vars_files:
    - secure.yml
