aws_access_key = ''
aws_secret_key = ''
BROKER_URL = ''
mongo_url = ''
bing_translate_id = ''
bing_translate_secret = ''
api_key = ''
# The grits histogram app communicates with the bsve api by proxying through the grits api.
# The BSVE api key, username, etc. here are used for authentication.
bsve_endpoint = ''
bsve_user_name = ''
bsve_api_key = ''
bsve_secret_key = ''
grits_curator_email = ''
grits_curator_password = ''
