version: '2'
services:
  flirt:
    container_name: flirt
    image: flirt
    environment:
      - "MONGO_URL=mongodb://${mongo_host}:${mongo_port}/flirt"
      - "MONGO_URI=mongodb://${mongo_host}:${mongo_port}"
      - "MONGO_HOST=${mongo_host}"
      - "MONGO_PORT=${mongo_port}"
      - MONGO_DB=flirt
      - SIMULATION_PORT=45000
      - "ROOT_URL=http://${ip_address}"
      - PORT=3000
      #- TERM=xterm
      - "SMTP_USER=${aws_smtp_user}"
      - "SMTP_PASSWORD=${aws_smtp_password}"
    ports:
      - "${flirt_port}:3000"
    restart: always
    volumes:
      - /shared/flirt:/shared:ro
    command: supervisord --nodaemon --config /etc/supervisor/supervisord.conf
