---
- file: path="/ibis" state=directory mode="a+rwx"
- name: Get get IBIS code
  git:
    repo: "https://github.com/ecohealthalliance/ibis.git"
    dest: "/ibis"
    recursive: no
    force: yes
- name: Add GIS repo
  apt_repository: repo="ppa:ubuntugis/ubuntugis-unstable" state=present
- shell: apt-get update
- name: Add GDAL packages
  shell: apt-get install -y gdal-bin python-gdal libgdal1-dev unzip
- pip:
    virtualenv: /ibis/venv
    virtualenv_python: python
    name: numpy
- pip:
    virtualenv: /ibis/venv
    virtualenv_python: python
    requirements: /ibis/.scripts/requirements.pip
- name: Install EpiTator dependencies
  shell: /ibis/venv/bin/python -m spacy download en_core_web_sm
- name: Install EpiTator dependencies
  shell: /ibis/venv/bin/python -m epitator.importers.import_disease_ontology
- name: Install EpiTator dependencies
  shell: /ibis/venv/bin/python -m epitator.importers.import_wikidata
- name: Download GPW data
  command: aws s3 cp s3://eha-flirt/gpw-v4-population-count-rev10_2015_15_min_tif.zip /ibis/.scripts/score_api
- command: unzip gpw-v4-population-count-rev10_2015_15_min_tif.zip -d gpw
  args:
    creates: /ibis/.scripts/score_api/gpw
    chdir: /ibis/.scripts
- block:
  - name: Run event ranking script
    shell: "/ibis/venv/bin/python rank_events.py{{additional_rank_event_params  | default('')}}"
    args:
      chdir: /ibis/.scripts/score_api
    register: rank_events_result
  always:
  - debug: var=rank_events_result.stdout_lines
  environment:
    MONGO_HOST: "mongodb://{{mongo_host}}"
