- name: Download image
  aws_s3:
    bucket: bsve-integration
    object: eidr-connect.tar.gz
    dest: /tmp/eidr-connect.tar.gz
    mode: get
    overwrite: "{{overwrite}}"
  register: image
- command: "gzip -dfk /tmp/eidr-connect.tar.gz"
  when: image.changed
- name: Load image into docker
  shell: "docker load < /tmp/eidr-connect.tar"
  when: image.changed
- name: Copy compose directory
  synchronize: src="compose/" dest="/{{ eidr_connect_domain_name }}-compose"
- name: Start services
  docker_service:
    # The compose directory must be unique for each service
    project_src: "/{{ eidr_connect_domain_name }}-compose"
  environment:
    ip_address: "{{ ansible_default_ipv4.address }}"
    domain_name: "{{ eidr_connect_domain_name }}"
    db_name: "{{ eidr_connect_db_name }}"
    port: "{{ eidr_connect_port }}"
- name: Restore database
  block:
  - name: Download eidr-connect database dump
    aws_s3:
      bucket: eidr-connect-backups
      object: mongodump-2017-10-10.tar.gz
      dest: /tmp/eidr-connect-dump.tar.gz
      mode: get
      overwrite: "{{overwrite}}"
    register: data
  - name: Create database dump directory
    file: path=/tmp/eidr-connect-dump state=directory
  - command: tar -xvzf /tmp/eidr-connect-dump.tar.gz -C /tmp/eidr-connect-dump
    when: data.changed
  - command: mongorestore --host localhost:27017 --drop /tmp/eidr-connect-dump/var/log/dump/eidr-connect/ --db eidr-connect
    when: data.changed
  when: eidr_connect_db_name == "eidr-connect"
