- hosts: targets
  remote_user: ubuntu
  become: true
  become_user: root
  vars:
    overwrite: different
  roles:
    - name: deploy-flirt
      tags: deploy-flirt
      flirt_port: 4080
    - name: deploy-grits
      tags:
        - deploy-grits
        - deploy-grits-without-worker
    - name: deploy-promed-scraper
      tags: deploy-promed-scraper
    - name: deploy-eidr-connect
      tags: deploy-eidr-connect
      eidr_connect_db_name: "eidr-connect"
      eidr_connect_domain_name: "eidr-connect.eha.io"
      eidr_connect_port: 3080
    - name: deploy-eidr-connect
      tags: deploy-eidr-connect-bsve
      eidr_connect_db_name: "eidr-connect-bsve"
      eidr_connect_domain_name: "eidr-connect-bsve.eha.io"
      eidr_connect_port: 3180
  vars_files:
    - my_secure.yml
- hosts: grits-workers
  remote_user: ubuntu
  become: true
  become_user: root
  vars:
    overwrite: different
  roles:
    - name: deploy-grits-worker
      tags:
        - deploy-grits
        - deploy-grits-worker
  vars_files:
    - my_secure.yml
