- hosts: localhost
  become: yes
  become_method: sudo
  roles:
    - name: provision-instances
      instance_size: "c4.large"
      aws_security_group: temp-instances
      key_name: temp-instances
      instance_tag: "ci-test-instance"
      host_group: ec2hosts
      tags: always
  vars_files:
    - my_secure.yml

- hosts: ec2hosts
  remote_user: ubuntu
  become: true
  become_user: root
  vars:
    ansible_vault_password: "{{ lookup('file', 'vault_pass') }}"
  pre_tasks:
    - name: Cancel prior shutdown commands
      shell: "shutdown -c || true"
    - name: Shut down the instance in one hour (to cancel use shutdown -c)
      shell: "shutdown -h +55 &"
  roles:
    - name: kamaln7.swapfile
      swapfile_size: 16GB
      swapfile_location: "/swapfile"
      tags: swap
    - name: angstwad.docker_ubuntu
      tags: docker
    - name: init
      tags: init
  tasks:
    - file: path="/shared/eidr-connect" state="directory"
    - name: Create sensitive-environment-vars.env
      copy: content="{{ eidr_connect_sensitive_envvars }}" dest="/shared/eidr-connect/sensitive-environment-vars.env" force=yes
    - file: path="/shared/eidr-connect/settings-dev.json"
    - name: Copy image directory
      synchronize: src="{{ docker_image_path }}" dest="/docker_image"
    - name: Build image
      command: "docker build -t eidr-connect-test -f /docker_image/test.Dockerfile /docker_image/"
    - name: Start app
      command: "docker-compose -f /docker_image/eidr-connect-test.yml up -d"
  vars_files:
    - my_secure.yml
