- hosts: targets
  remote_user: ubuntu
  become: true
  become_user: root
  tasks:
  - file: path="/eidr-connect" state=directory mode="a+rwx"
  - name: Get get EIDR-C code
    git:
      repo: "https://github.com/ecohealthalliance/eidr-connect.git"
      dest: "/eidr-connect"
      recursive: no
      force: yes
  - name: Add pdftohtml package
    shell: apt-get install -y pdftohtml
  - pip:
      virtualenv: /eidr-connect/venv
      virtualenv_python: python
      name: "{{item}}"
    with_items:
      - requests
      - pandas
      - pymongo
      - backports.functools_lru_cache
      - bs4
  - block:
    - name: Run India MOH data download script
      shell: /eidr-connect/venv/bin/python download_india_moh_data.py /tmp
      args:
        chdir: /eidr-connect/.scripts
      register: result
    always:
    - debug: var=result.stdout_lines
    environment:
      MONGO_HOST: "mongodb://localhost:27017"

  - block:
    - name: Run EpiArchive download script
      shell: /eidr-connect/venv/bin/python download_epi_archive_data.py
      args:
        chdir: /eidr-connect/.scripts
      async: 100000000000
      register: epiarchive_worker
    - name: ECDC CDTR download script
      shell: /eidr-connect/venv/bin/python download_ECDC_CDTRs.py
      args:
        chdir: /eidr-connect/.scripts
    - name: Wait for worker
      async_status:
        jid: "{{ epiarchive_worker.ansible_job_id }}"
      register: result
      until: result.finished
      retries: 60
      delay: 240
    always:
    - debug: var=result.stdout_lines
    environment:
      MONGO_HOST: "mongodb://localhost:27017"
      PYTHONIOENCODING: "utf-8"
