---
- name: Create backup_to_s3 script
  template: src=backup_to_s3.sh.j2 dest=~/backup_to_s3.sh mode="a+rwx"
- name: Creating dump database cronjob
  cron:
    name: "Dump database"
    minute: "0"
    hour: "5"
    weekday: "6"
    job: "~/backup_to_s3.sh"
- name: Create virtuoso restart cronjob
  cron:
    name: "Restart virtuoso to avoid memory leak"
    minute: "0"
    hour: "5"
    weekday: "1"
    job: "/usr/bin/docker restart virtuoso-container"
